SELECT f.SCHEMA_NAME AS SCHEMA_NAME,
       f.FUNCTION_NAME AS function_name,
       f.INPUT_PARAMETER_COUNT AS input_parameter_count,
       f.RETURN_VALUE_COUNT AS return_value_count,
       f.DEFINITION AS definition,
       f.IS_VALID AS is_valid,
       f.OWNER_NAME AS owner_name,
       f.CREATE_TIME AS create_time
FROM SYS.FUNCTIONS f
WHERE f.SCHEMA_NAME NOT IN('SYS',
                           '_SYS_BI',
                           '_SYS_EPM',
                           '_SYS_REPO',
                           '_SYS_RT',
                           'SAP_PA_APL',
                           'SAP_XS_LM_PE',
                           '_SYS_AFL',
                           '_SYS_DI',
                           '_SYS_STATISTICS',
                           'SAP_REST_API',
                           'UIS',
                           '_SYS_BIC',
                           'HANA_XS_BASE',
                           '_SYS_WORKLOAD_REPLAY',
                           '_SYS_PLAN_STABILITY',
                           '_SYS_TELEMETRY',
                           '_SYS_SECURITY',
                           '_SYS_AUDIT',
                           '_SYS_TASK',
                           '_SYS_XS',
                           'SAP_XS_LM',
                           'SAP_XS_USAGE',
                           '_SYS_DATA_ANONYMIZATION',
                           '_SYS_SQL_ANALYZER')
ORDER BY f.SCHEMA_NAME,
         f.FUNCTION_NAME;