# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'ci:run')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir: ['./rdbms2datacatalog', './rdbmscsv2datacatalog', './postgresql2datacatalog', './greenplum2datacatalog', './redshift2datacatalog', './sqlserver2datacatalog', './mysql2datacatalog', './teradata2datacatalog', './oracle2datacatalog', './vertica2datacatalog']
        python-version: [3.6, 3.7]
    defaults:
      run:
        working-directory: ${{ matrix.build-dir }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 yapf
        # [TODO] Remove this once we publish do PYPI.
        pip install ./lib/datacatalog_connectors_commons-1.0.0-py2.py3-none-any.whl
        pip install ./lib/datacatalog_connectors_commons_test-1.0.0-py2.py3-none-any.whl
        pip install pytest mock pytest-cov
        if [ -f ./lib/rdbms2datacatalog-1.0.0-py2.py3-none-any.whl ]; then pip install ./lib/rdbms2datacatalog-1.0.0-py2.py3-none-any.whl; fi
        if [ -f ./lib/postgresql2datacatalog-1.0.0-py2.py3-none-any.whl ]; then pip install ./lib/postgresql2datacatalog-1.0.0-py2.py3-none-any.whl; fi
    - name: Formatting rules with yapf
      run: |
        # stop the build if formatting is different from yapf
        yapf --diff --recursive src tests  
    - name: Lint with flake8
      run: |
        flake8 src tests
    - name: Test with pytest
      run: |
        python setup.py test
