# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build-dir: ['./google-datacatalog-rdbms-connector', './google-datacatalog-rdbmscsv-connector', './google-datacatalog-postgresql-connector', './google-datacatalog-greenplum-connector', './google-datacatalog-redshift-connector', './google-datacatalog-sqlserver-connector', './google-datacatalog-mysql-connector', './google-datacatalog-teradata-connector', './google-datacatalog-oracle-connector', './google-datacatalog-vertica-connector', './google-datacatalog-saphana-connector']
        python-version: [3.6, 3.7, 3.8]
    defaults:
      run:
        working-directory: ${{ matrix.build-dir }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 yapf
        # Update the commons RDBMS library with the local version
        pip install ../google-datacatalog-rdbms-connector
        # Update the commons PostgreSQL library with the local version
        # Greenplum and Redshift connectors leverage this.
        pip install ../google-datacatalog-postgresql-connector
        pip install .
    - name: Formatting rules with yapf
      run: |
        # stop the build if formatting is different from yapf
        yapf --diff --recursive src tests  
    - name: Lint with flake8
      run: |
        flake8 src tests
    - name: Test with pytest
      run: |
        python setup.py test
